sonar.projectKey=darynatertychna_sonar
sonar.organization=darynatertychna
sonar.projectVersion=1.0

sonar.sources=crime-api
sonar.tests=crime-api


sonar.test.inclusions=crime-api/test_*.py,crime-api/tests/**/*.py
sonar.exclusions=**/venv/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml