sonar.projectKey=darynatertychna_sonar
sonar.organization=darynatertychna

sonar.sources=crime-api
sonar.exclusions=**/venv/**,**/__pycache__/**,**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml