sonar.projectKey=darynatertychna_sonar
sonar.organization=darynatertychna
sonar.projectVersion=1.0

sonar.sources=crime-api
sonar.exclusions=**/venv/**,**/__pycache__/**,**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml